# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndroid:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.4
          
      - name: Cache haxelib path
        uses: actions/cache@v2
        with:
          path: |
            %~/haxelib%
          key: ${{ runner.os }}-android
          
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: '11'
        
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      # Runs a set of commands using the runners shell
      - name: Install haxelib stuff
        run: |
          haxelib --quiet install lime
          haxelib --quiet install openfl
          haxelib --quiet install flixel
          haxelib --quiet --always run lime setup flixel
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install hscript --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git extension-androidtools https://github.com/jigsaw-4277821/extension-androidtools --quiet
          haxelib git extension-webview https://github.com/Daninnocent/extension-webview.git --quiet
          haxelib git linc_luajit https://github.com/jigsaw-4277821/linc_luajit.git --quiet
          haxelib list

      - name: Config Lime stuff
        run: |
          haxelib run lime setup -alias -y
          lime config ANDROID_SDK $ANDROID_HOME
          lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
          lime config JAVA_HOME $JAVA_HOME
          lime config ANDROID_SETUP true
          lime config
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: haxelib run lime build android -final
          
      - name: Publish Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug
